import { designTokens as t } from '@examples/design-system';
import { docsTokens as dt, styles } from './typestyles';

const bp = '@media (max-width: 768px)';

const sidebarBase = styles.component('docs-sidebar', {
  root: {
    width: dt.size.sidebarWidth,
    flexShrink: 0,
    height: '100vh',
    position: 'sticky',
    top: 0,
    display: 'flex',
    flexDirection: 'column',
    borderRight: `${t.borderWidth.thick} solid #000`,
    [bp]: {
      position: 'fixed',
      height: 'auto',
      top: 0,
      left: 0,
      bottom: 0,
      zIndex: 200,
      transform: 'translateX(-100%)',
      visibility: 'hidden',
      backgroundColor: t.color.background.app,
    },
  },
  rootOpen: {
    [bp]: {
      transform: 'translateX(0)',
      visibility: 'visible',
    },
  },
  backdrop: {
    display: 'none',
    [bp]: {
      display: 'block',
      position: 'fixed',
      inset: 0,
      zIndex: 100,
      backgroundColor: t.color.overlay.default,
      opacity: 0,
      visibility: 'hidden',
    },
  },
  backdropVisible: {
    [bp]: {
      opacity: 1,
      visibility: 'visible',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: `${t.space[5]} ${t.space[5]} ${t.space[4]}`,
  },
  logo: {
    fontSize: t.fontSize.xl,
    fontWeight: t.fontWeight.bold,
    color: t.color.text.primary,
    textDecoration: 'none',
    letterSpacing: '-0.03em',
    textTransform: 'uppercase',
    '&:hover': { color: t.color.accent.default },
  },
  logoAccent: {
    color: t.color.accent.default,
  },
  search: {
    margin: `0 ${t.space[4]} ${t.space[4]}`,
    padding: `${t.space[2]} ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    backgroundColor: t.color.background.subtle,
    color: t.color.text.secondary,
    outline: 'none',
    '&:focus': { borderColor: t.color.accent.default },
    '&::placeholder': { color: t.color.text.placeholder },
  },
  searchWrapper: {
    position: 'relative',
    borderTop: `${t.borderWidth.thick} solid #000`,
    borderBottom: `${t.borderWidth.thick} solid #000`,
  },
  searchIcon: {
    position: 'absolute',
    left: dt.size.insetXs,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: t.color.text.placeholder,
    pointerEvents: 'none',
    lineHeight: 0,
  },
  searchInput: {
    width: '100%',
    padding: `${t.space[2]} ${t.space[4]} ${t.space[2]} 32px`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    border: 'none',
    backgroundColor: 'transparent',
    color: t.color.text.secondary,
    outline: 'none',
    '&:focus': {
      backgroundColor: t.color.background.subtle,
    },
    '&::placeholder': { color: t.color.text.placeholder },
  },
  searchKbd: {
    position: 'absolute',
    right: dt.size.insetXs,
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: t.fontSize.xs,
    color: t.color.text.placeholder,
    backgroundColor: t.color.background.surface,
    border: `${t.borderWidth.thin} solid #000`,
    boxShadow: t.shadow.xs,
    padding: `${t.space[1]} 5px`,
    fontFamily: t.fontFamily.sans,
    lineHeight: dt.size.lineHeightTight,
    pointerEvents: 'none',
  },
  searchTrigger: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    margin: 0,
    padding: `${t.space[2]} ${t.space[4]} ${t.space[2]} 32px`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    textAlign: 'left',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    color: t.color.text.secondary,
    outline: 'none',
    '&:hover': {
      backgroundColor: t.color.background.subtle,
      color: t.color.text.primary,
    },
    '&:focus-visible': {
      outline: `${t.borderWidth.thin} solid ${t.color.accent.default}`,
      outlineOffset: '-2px',
    },
  },
  nav: {
    flex: 1,
    overflowY: 'auto',
    padding: `0 ${t.space[4]}`,
  },
  section: {
    marginBottom: t.space[2],
  },
  sectionTitle: {
    fontSize: t.fontSize.xs,
    fontWeight: t.fontWeight.bold,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: t.color.text.placeholder,
    padding: `${t.space[2]} ${t.space[2]}`,
    marginTop: t.space[2],
  },
  link: {
    display: 'block',
    fontSize: t.fontSize.md,
    color: t.color.text.secondary,
    textDecoration: 'none',
    padding: `6px ${t.space[2]}`,
    borderLeft: `${t.borderWidth.default} solid transparent`,
    '&:hover': {
      color: t.color.text.primary,
      backgroundColor: t.color.background.subtle,
    },
  },
  linkActive: {
    color: t.color.accent.default,
    fontWeight: t.fontWeight.medium,
    backgroundColor: t.color.accent.subtle,
    borderLeftColor: t.color.accent.default,
    '&:hover': {
      color: t.color.accent.default,
      backgroundColor: t.color.accent.subtle,
    },
  },
  footer: {
    padding: `${t.space[4]} ${t.space[5]}`,
    borderTop: `${t.borderWidth.thick} solid #000`,
    display: 'flex',
    flexDirection: 'column',
    gap: t.space[2],
  },
  themeFieldLabel: {
    fontSize: t.fontSize.xs,
    fontWeight: t.fontWeight.bold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: t.color.text.placeholder,
  },
  themeSelect: {
    width: '100%',
    padding: `${t.space[2]} ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    backgroundColor: t.color.background.surface,
    border: `${t.borderWidth.default} solid #000`,
    color: t.color.text.primary,
    cursor: 'pointer',
    outline: 'none',
    boxShadow: t.shadow.xs,
    '&:focus': {
      outline: `${t.borderWidth.thin} solid ${t.color.accent.default}`,
      outlineOffset: '0',
    },
  },
  themeToggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: t.space[2],
    width: '100%',
    padding: `7px ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    color: t.color.text.primary,
    backgroundColor: t.color.background.surface,
    border: `${t.borderWidth.default} solid #000`,
    cursor: 'pointer',
    fontFamily: t.fontFamily.sans,
    boxShadow: t.shadow.xs,
    '&:hover': {
      backgroundColor: t.color.background.subtle,
    },
  },
});

export const sidebar = sidebarBase;
