import { styles } from 'typestyles';
import { designTokens as t } from './tokens';

/** Command / search palette overlay (⌘K-style). */
export const commandPalette = styles.create('command-palette', {
  root: {
    position: 'fixed',
    inset: 0,
    zIndex: 450,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: `max(12vh, 72px) ${t.space.lg} ${t.space.xl}`,
    pointerEvents: 'none',
    opacity: 0,
    visibility: 'hidden',
    transition: t.transition.overlayFade,
  },
  rootOpen: {
    pointerEvents: 'auto',
    opacity: 1,
    visibility: 'visible',
  },
  backdrop: {
    position: 'absolute',
    inset: 0,
    backgroundColor: t.color.backdropTint,
    transition: t.transition.backdrop,
    '@supports (backdrop-filter: blur(1px))': {
      backdropFilter: 'blur(10px)',
    },
  },
  dialog: {
    position: 'relative',
    zIndex: 1,
    width: 'min(560px, 100%)',
    maxHeight: 'min(72vh, 640px)',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: t.font.family,
    backgroundColor: t.color.surface,
    borderRadius: t.radius.lg,
    border: `1px solid ${t.color.border}`,
    boxShadow: t.shadow.elevated,
    overflow: 'hidden',
    opacity: 0,
    transition: t.transition.panelEnter,
  },
  dialogOpen: {
    opacity: 1,
  },
  inputRow: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: t.space.sm,
    padding: `${t.space.md} ${t.space.lg}`,
    borderBottom: `1px solid ${t.color.border}`,
  },
  inputIcon: {
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    color: t.color.textPlaceholder,
    lineHeight: 0,
  },
  input: {
    flex: 1,
    minWidth: 0,
    border: 'none',
    margin: 0,
    padding: 0,
    backgroundColor: 'transparent',
    fontSize: t.font.sizeLg,
    fontFamily: t.font.family,
    color: t.color.text,
    outline: 'none',
    '&::placeholder': { color: t.color.textPlaceholder },
  },
  results: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    margin: 0,
    padding: `${t.space.xs} 0 ${t.space.sm}`,
    listStyle: 'none',
  },
  result: {
    margin: 0,
  },
  resultLink: {
    display: 'block',
    padding: `${t.space.sm} ${t.space.lg}`,
    textDecoration: 'none',
    color: t.color.text,
    transition: t.transition.surfaceFast,
    '&:hover': {
      backgroundColor: t.color.accentWash,
    },
  },
  resultLinkActive: {
    backgroundColor: t.color.accentWash,
  },
  resultTitle: {
    display: 'block',
    fontSize: t.font.sizeMd,
    fontWeight: t.font.weightSemibold,
    lineHeight: 1.35,
    marginBottom: t.space.xs,
  },
  resultMeta: {
    display: 'block',
    fontSize: t.font.sizeSm,
    color: t.color.textMuted,
    lineHeight: 1.35,
  },
  mark: {
    fontFamily: 'inherit',
    backgroundColor: t.color.markHighlight,
    color: t.color.text,
    borderRadius: t.radius.sm,
    padding: `0 ${t.space.xs}`,
  },
  empty: {
    padding: `${t.space.lg} ${t.space.lg}`,
    fontSize: t.font.sizeSm,
    color: t.color.textMuted,
    lineHeight: 1.5,
  },
});
